# Generated by Django 4.2.1 on 2023-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'categoría de productos',
                'verbose_name_plural': 'categorías de productos',
            },
        ),
    ]
