# Generated by Django 4.2.1 on 2023-05-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='foto',
            field=models.URLField(null=True),
        ),
    ]
