# Generated by Django 4.2.1 on 2023-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('foto', models.URLField()),
            ],
            options={
                'verbose_name': 'categoría de destino',
                'verbose_name_plural': 'categorías de destinos',
            },
        ),
    ]
